[project]
name = "kappybara"
version = "0.1.3"
description = "Work with Kappa rule-based models in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lark>=1.2.2",
    "pandas>=2.0.0",
    "matplotlib>=3.10.3",
]

[project.urls]
Homepage = "https://kappybara.io"
Documentation = "https://kappybara.io/api/index.html"
Repository = "https://github.com/berkalpay/kappybara"
Issues = "https://github.com/berkalpay/kappybara/issues"

[tool.setuptools.package-data]
kappybara = ["*.lark"]

[tool.uv]
dev-dependencies = [
  "kappybara",
  "py-spy>=0.4.0",
  "pytest",
  "black",
  "mypy>=1.15.0",
  "memory-profiler>=0.61.0",
  "pandas>=2.0.0",
  "matplotlib>=3.10.3",
]

[tool.uv.sources]
kappybara = { workspace = true }

[tool.pytest.ini_options]
testpaths = [
  "tests",
  "kappybara",
]
norecursedirs = [
  ".*",
  "*site-packages*",
  "*dist-packages*",
]
python_files = [
  "*.py",
]
python_functions = [ "test_*" ]
