name: cpu-profiles
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

  # Manual trigger
  workflow_dispatch:

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.5"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run profiler
        continue-on-error: true
        run: |
             cd tests/cpu-profiles
             uv run bash run_profiler.sh

      - name: Export profiler artifacts
        uses: actions/upload-artifact@v4
        with:
            name: cpu-profiles
            path: "tests/cpu-profiles/results/*"
