# From https://www.sphinx-doc.org/en/master/tutorial/deploying.html

name: "docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: ".python-version"
    - name: Install Pandoc
      uses: pandoc/actions/setup@v1
    - name: Install dependencies
      run: |
        pip install sphinx pydata-sphinx-theme matplotlib nbsphinx ipykernel
        pip install .
    - name: Build HTML
      run: |
        sphinx-build docs/source docs/build/html
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
        cname: kappybara.io
